# Generated by Django 5.1 on 2024-09-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='flowers.order'),
        ),
    ]
