# Generated by Django 5.1 on 2024-09-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_remove_orderitem_amount_remove_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='products',
        ),
    ]
