# Generated by Django 5.1 on 2024-09-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0009_rename_products_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
