# Generated by Django 5.1 on 2024-09-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0010_rename_products_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
