# Generated by Django 5.1 on 2024-09-23 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0013_rename_sale_data_report_total_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='report',
            name='profit',
        ),
        migrations.AddField(
            model_name='report',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
