# Generated by Django 5.1 on 2024-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0014_remove_report_expenses_remove_report_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='Самовывоз', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Наличные', max_length=100),
        ),
    ]
